### ISSUE TITLE
Environment fordítása hogyan?

### ISSUE THREAD

**Issue by tanarurkerem** [laravelhungary/docs#3]
Hogyan fordítsuk?

Environment az "Környezet", vagy "Futtató környezet" legyen?

**Comment by nxu** [comment]
Szerintem mindketto rendben van, de a futtato környezet talan egyertelmubben kifejezi, mirol van szo. 
Ha tobbszor is szoba kerul az adott oldalon, akkor viszont feleslegesnek tartom ismetelgetni.
